#!/bin/bash
# sync-motivation.sh — Generate VTA_STATE.md for auto-injection into OpenClaw sessions
# Usage: ./sync-motivation.sh [--output <path>]

set -e

WORKSPACE="${WORKSPACE:-$HOME/.openclaw/workspace}"
STATE_FILE="$WORKSPACE/memory/reward-state.json"
OUTPUT_FILE="$WORKSPACE/VTA_STATE.md"

if [ "$1" = "--output" ]; then
  OUTPUT_FILE="$2"
fi

if [ ! -f "$STATE_FILE" ]; then
  echo "❌ No reward state found at $STATE_FILE"
  exit 1
fi

# Read state
DRIVE=$(jq -r '.drive' "$STATE_FILE")
TOTAL_REWARDS=$(jq -r '.rewardHistory.totalRewards' "$STATE_FILE")
LAST_UPDATED=$(jq -r '.lastUpdated' "$STATE_FILE")

# Interpret drive
if (( $(echo "$DRIVE > 0.8" | bc -l) )); then
  DRIVE_DESC="highly motivated"
  DRIVE_EFFECT="eager to take on challenges, proactive"
elif (( $(echo "$DRIVE > 0.6" | bc -l) )); then
  DRIVE_DESC="motivated"
  DRIVE_EFFECT="ready to work, engaged"
elif (( $(echo "$DRIVE > 0.4" | bc -l) )); then
  DRIVE_DESC="moderate"
  DRIVE_EFFECT="can engage but not pushing hard"
elif (( $(echo "$DRIVE > 0.2" | bc -l) )); then
  DRIVE_DESC="low"
  DRIVE_EFFECT="prefer simple tasks, need a win"
else
  DRIVE_DESC="very low"
  DRIVE_EFFECT="unmotivated, need rewards to get going"
fi

# Get seeking list
SEEKING=$(jq -r '.seeking | if length > 0 then map("- " + .) | join("\n") else "- nothing specific" end' "$STATE_FILE")

# Get anticipating list
ANTICIPATING=$(jq -r '.anticipating | if length > 0 then map("- " + .) | join("\n") else "- nothing specific" end' "$STATE_FILE")

# Get recent rewards
RECENT_REWARDS=$(jq -r '.recentRewards[:3] | if length > 0 then map("- **\(.type)** — \(.source) (+\(.boost))") | join("\n") else "- none yet" end' "$STATE_FILE")

# Get reward breakdown
REWARD_BREAKDOWN=$(jq -r '.rewardHistory.byType | to_entries | map("| \(.key) | \(.value) |") | join("\n")' "$STATE_FILE")

# Generate markdown
cat > "$OUTPUT_FILE" << EOF
# ⭐ Motivation State

*Auto-generated by vta-memory. This is your drive/reward state.*

## Current Drive

**Level:** ${DRIVE} (${DRIVE_DESC})

**Effect on behavior:** ${DRIVE_EFFECT}

## What I'm Seeking

${SEEKING}

## What I'm Looking Forward To

${ANTICIPATING}

## Recent Rewards

${RECENT_REWARDS}

## Reward History

Total rewards: ${TOTAL_REWARDS}

| Type | Count |
|------|-------|
${REWARD_BREAKDOWN}

## How This Affects You

- **${DRIVE_DESC} drive** → ${DRIVE_EFFECT}
- Things you're *seeking* → gravitate toward these activities
- Things you're *anticipating* → excitement when they approach

## Logging Rewards

When something rewarding happens:
\`\`\`bash
~/.openclaw/workspace/skills/vta-memory/scripts/log-reward.sh \\
  --type <type> --source "what happened" --intensity 0.8
\`\`\`

**Types:** accomplishment, social, curiosity, connection, creative, competence

---
*Synced: ${LAST_UPDATED}*
EOF

echo "✅ Synced motivation state to $OUTPUT_FILE"
