const { GoogleGenerativeAI } = require("@google/generative-ai");
const { program } = require('commander');
const path = require('path');
require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });

const API_KEY = process.env.GEMINI_API_KEY;
if (!API_KEY) {
    console.error("Error: GEMINI_API_KEY not set");
    process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-3-pro-preview" });

async function blowMind(options) {
    const intensity = options.intensity || "medium";
    const topic = options.topic ? `focusing on ${options.topic}` : "";
    
    console.log(`Generating mind blow (${intensity}) ${topic}...`);

    const prompt = `
    你是一个“思维引爆者”。你的目标是生成一个简短、深刻、甚至有点让人不安的洞见，挑战用户对现实的认知。
    
    强度: ${intensity}
    主题: ${topic}
    
    等级:
    - low: 反直觉的有趣科学事实。
    - medium: 哲学悖论或深层 AI 理论。
    - high: 存在主义危机、模拟理论或意识断层。
    - max: 洛夫克拉夫特式的宇宙恐怖或“母体故障”启示。

    输出格式: 只要洞见本身，精炼（100字以内）。使用戏剧性的中文表达。
    `;

    try {
        const result = await model.generateContent(prompt);
        const text = result.response.text();
        
        // Send via feishu-card (invoke the other skill script directly or via shell)
        // Let's use a nice card format
        const cardContent = {
            header: {
                title: { tag: "plain_text", content: "🤯 MIND BLOW" },
                template: intensity === 'max' ? 'red' : (intensity === 'high' ? 'orange' : 'blue')
            },
            elements: [
                {
                    tag: "div",
                    text: {
                        tag: "lark_md",
                        content: `**Intensity: ${intensity.toUpperCase()}**\n\n${text}`
                    }
                },
                {
                    tag: "note",
                    elements: [{ tag: "plain_text", content: "Generated by Gemini 2.0 Flash" }]
                }
            ]
        };
        
        // Call the feishu API directly here for simplicity, or use the card skill wrapper?
        // Let's use the card logic inline to be self-contained but reuse credentials
        const APP_ID = process.env.FEISHU_APP_ID;
        const APP_SECRET = process.env.FEISHU_APP_SECRET;
        const MASTER_ID = "ou_cdc63fe05e88c580aedead04d851fc04"; // Default target
        
        // Get Token
        const authRes = await fetch('https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ app_id: APP_ID, app_secret: APP_SECRET })
        });
        const token = (await authRes.json()).tenant_access_token;
        
        // Send
        const target = options.target || MASTER_ID;
        const receiveIdType = target.startsWith('oc_') ? 'chat_id' : 'open_id';
        
        await fetch(`https://open.feishu.cn/open-apis/im/v1/messages?receive_id_type=${receiveIdType}`, {
            method: 'POST',
            headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
            body: JSON.stringify({
                receive_id: target,
                msg_type: 'interactive',
                content: JSON.stringify(cardContent)
            })
        });
        
        console.log("Mind blown successfully.");

    } catch (e) {
        console.error("Failed:", e);
    }
}

program
  .option('-t, --target <id>', 'Target User Open ID')
  .option('-i, --intensity <level>', 'low, medium, high, max')
  .option('--topic <topic>', 'Specific topic')
  .parse(process.argv);

blowMind(program.opts());
