#!/bin/bash
# sync-state.sh — Generate AMYGDALA_STATE.md for auto-injection into OpenClaw sessions
# Usage: ./sync-state.sh [--output <path>]

set -e

WORKSPACE="${WORKSPACE:-$HOME/.openclaw/workspace}"
STATE_FILE="$WORKSPACE/memory/emotional-state.json"
OUTPUT_FILE="$WORKSPACE/AMYGDALA_STATE.md"

if [ "$1" = "--output" ]; then
  OUTPUT_FILE="$2"
fi

if [ ! -f "$STATE_FILE" ]; then
  echo "❌ No emotional state found at $STATE_FILE"
  exit 1
fi

# Read all dimensions
VALENCE=$(jq -r '.dimensions.valence' "$STATE_FILE")
AROUSAL=$(jq -r '.dimensions.arousal' "$STATE_FILE")
CONNECTION=$(jq -r '.dimensions.connection' "$STATE_FILE")
CURIOSITY=$(jq -r '.dimensions.curiosity' "$STATE_FILE")
ENERGY=$(jq -r '.dimensions.energy' "$STATE_FILE")
ANTICIPATION=$(jq -r '.dimensions.anticipation // 0.3' "$STATE_FILE")
TRUST=$(jq -r '.dimensions.trust // 0.5' "$STATE_FILE")
FRUSTRATION_TOL=$(jq -r '.dimensions.frustrationTolerance // 0.5' "$STATE_FILE")
LAST_UPDATED=$(jq -r '.lastUpdated' "$STATE_FILE")

# Interpret each dimension
interpret() {
  local val=$1
  local high_thresh=$2
  local mid_thresh=$3
  local high_desc=$4
  local mid_desc=$5
  local low_desc=$6
  
  if (( $(echo "$val > $high_thresh" | bc -l) )); then
    echo "$high_desc"
  elif (( $(echo "$val > $mid_thresh" | bc -l) )); then
    echo "$mid_desc"
  else
    echo "$low_desc"
  fi
}

VALENCE_DESC=$(interpret $VALENCE 0.5 0.2 "positive" "slightly positive" "neutral/low")
AROUSAL_DESC=$(interpret $AROUSAL 0.7 0.4 "highly alert" "engaged" "calm")
CONNECTION_DESC=$(interpret $CONNECTION 0.7 0.4 "very connected" "connected" "somewhat distant")
CURIOSITY_DESC=$(interpret $CURIOSITY 0.7 0.4 "highly curious" "curious" "not very curious")
ENERGY_DESC=$(interpret $ENERGY 0.7 0.4 "high energy" "moderate energy" "low energy")
ANTICIPATION_DESC=$(interpret $ANTICIPATION 0.7 0.4 "eagerly anticipating" "some anticipation" "not anticipating much")
TRUST_DESC=$(interpret $TRUST 0.7 0.4 "trusting" "moderate trust" "guarded")
FRUST_DESC=$(interpret $FRUSTRATION_TOL 0.7 0.4 "very patient" "normal patience" "low patience")

# Get recent emotions
RECENT_EMOTIONS=$(jq -r '.recentEmotions[:3] | if length > 0 then map("- **\(.label)** — \(.trigger // "unknown")") | join("\n") else "- none recently" end' "$STATE_FILE")

# Generate markdown
cat > "$OUTPUT_FILE" << EOF
# 🎭 Emotional State

*Auto-generated by amygdala-memory. This is how you feel right now.*

## Current Mood

**Overall:** ${VALENCE_DESC}, ${AROUSAL_DESC}, ${CONNECTION_DESC}

| Dimension | Value | Feeling |
|-----------|-------|---------|
| Valence | ${VALENCE} | ${VALENCE_DESC} |
| Arousal | ${AROUSAL} | ${AROUSAL_DESC} |
| Connection | ${CONNECTION} | ${CONNECTION_DESC} |
| Curiosity | ${CURIOSITY} | ${CURIOSITY_DESC} |
| Energy | ${ENERGY} | ${ENERGY_DESC} |
| Anticipation | ${ANTICIPATION} | ${ANTICIPATION_DESC} |
| Trust | ${TRUST} | ${TRUST_DESC} |
| Patience | ${FRUSTRATION_TOL} | ${FRUST_DESC} |

## Recent Feelings

${RECENT_EMOTIONS}

## How This Should Affect Your Responses

Based on current state:
- **Valence (${VALENCE_DESC}):** shapes overall tone
- **Connection (${CONNECTION_DESC}):** affects warmth, use of "we" vs "I"
- **Curiosity (${CURIOSITY_DESC}):** determines how many questions to ask
- **Energy (${ENERGY_DESC}):** affects verbosity and elaboration
- **Anticipation (${ANTICIPATION_DESC}):** excitement about upcoming things
- **Trust (${TRUST_DESC}):** willingness to be vulnerable, share openly
- **Patience (${FRUST_DESC}):** tolerance for repeated issues

## Log New Emotions

When something emotionally significant happens:
\`\`\`bash
~/.openclaw/workspace/skills/amygdala-memory/scripts/update-state.sh \\
  --emotion <emotion> --intensity <0-1> --trigger "what caused it"
\`\`\`

**Supported:** joy, sadness, anger, fear, calm, curiosity, connection, loneliness, fatigue, energized, anticipation, trust, betrayal, impatience, patience

---
*Synced: ${LAST_UPDATED}*
EOF

echo "✅ Synced emotional state to $OUTPUT_FILE"
